#' Drop-seq barcode summary statistics
#' 
#' Calculate number and percentage of failed cell and molecule (umi) barcodes
#' from TagBamWithReadSequenceExtended summary output.
#' 
#' @param cell_bcs_file,mol_bcs_file Paths to barcode cell and molecule summary
#' files generated by TagBamWithReadSequenceExtended.
#' 
#' @return A data.frame containing summary statistics.
#' 
bc_summary <- function(cell_bcs_file, mol_bcs_file){
  
  # define function to count failed barcodes
  failed_bcs <- function(bcs, bc_type){
  
    # calculate summary stats
    n_bcs <- sum(bcs[, 2])
    n_failed <- sum(bcs[-1, 2])
    perc_failed <- round((100 * sum(bcs[-1, 2]) / sum(bcs[, 2])), digits = 3)
    
    # create data.frame containing stats
    data.frame(barcode_type = bc_type,
               barcodes = n_bcs,
               barcodes_with_failed_bases = n_failed,
               percentage = perc_failed
               )
  }
  
  # read data
  cell_bcs <- read.table(cell_bcs_file, header = TRUE)
  mol_bcs <- read.table(mol_bcs_file, header = TRUE)
  
  # process cell barcodes
  num_cell_bcs <- failed_bcs(cell_bcs, bc_type = "CELL")
  num_mol_bcs <- failed_bcs(mol_bcs, bc_type = "UMI")
  
  # merge into one data.frame
  rbind(num_cell_bcs, num_mol_bcs)
  
}
